management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    url: j${DATABASE_CONNECTION_URL:dbc:mariadb://db:3306/person}
    driver-class-name: "org.mariadb.jdbc.Driver"
  jpa:
    generate-ddl: ${JPA_GENERATE_DDL:true}
server:
  port: ${SERVICE_PORT:8080}


