version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: person
    ports:
      - 3306:3306

  person-service:
    image: localhost:5000/demo
    environment:
      SPRING_PROFILES_ACTIVE: compose
    ports:
      - 8888:8080
    depends_on:
      - db
    links:
      - db